package TicketVending;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *******************************************************************************
 * File name - AboutJDialog.java
 * <br>Description This is the About JDialog to display information about the
 * software. what is its function, what it does, contact information, copyright,
 * reserve rights.
 * <br>Created on 11/27/2017 Window 10, NetBeans 8.2, jdk 1.8.0_144
 *
 * @author Anh Dao
 * @version 2.0  <pre>
 *   project:       Project #3, Box office ticket vending technology.
 *   platform:      JDK 1.8.0_144
 *   IDE:           Netbeans 8.2
 *   course:        CS141, 2810, 2:50PM
 *   hours:         17 hours
 * </pre>
 *
 * @see java.awt.Color
 * @see javax.swing.JPanel
 * ****************************************************************************
 */
public class AboutJDialog extends javax.swing.JDialog {

    public String movieInfo = "";

    /**
     * initialize when start the dialog
     * @param parent create a new frame that About JDialog uses to show information of the software
     * @param modal frame uses modal of the movie software
     */
    public AboutJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //set color background
        this.getContentPane().setBackground(new Color(255, 255, 0));
        //center the form on startup
        this.setLocationRelativeTo(null);
        //set the Calculate button as default
        this.getRootPane().setDefaultButton(closeJButton);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        warningJLabel = new javax.swing.JLabel();
        googleLogoJLabel = new javax.swing.JLabel();
        polygonsJScrollPane = new javax.swing.JScrollPane();
        aboutJTextArea = new javax.swing.JTextArea();
        headerJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        exitJLabel = new javax.swing.JLabel();
        logoLabel4 = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        logoLabel7 = new javax.swing.JLabel();
        logoLabel8 = new javax.swing.JLabel();
        logoLabel6 = new javax.swing.JLabel();
        authorJLabel = new javax.swing.JLabel();
        getinTouchJLabel = new javax.swing.JLabel();
        twitterLogoJLabel = new javax.swing.JLabel();
        facebookLogoJLabel = new javax.swing.JLabel();
        logoLabel1 = new javax.swing.JLabel();
        logoLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regular Polygons 1.0 About");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeJButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        closeJButton.setForeground(new java.awt.Color(0, 102, 51));
        closeJButton.setText("Close");
        closeJButton.setSelected(true);
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 96, -1));

        warningJLabel.setBackground(new java.awt.Color(0, 102, 51));
        warningJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        warningJLabel.setForeground(new java.awt.Color(204, 204, 204));
        warningJLabel.setText("© All Rights Reserved 2017");
        getContentPane().add(warningJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        googleLogoJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        googleLogoJLabel.setForeground(new java.awt.Color(0, 102, 51));
        googleLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google_Plus_30px.png"))); // NOI18N
        googleLogoJLabel.setText("f");
        getContentPane().add(googleLogoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 30, 30));

        polygonsJScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        polygonsJScrollPane.setToolTipText("");
        polygonsJScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        polygonsJScrollPane.setViewportBorder(new javax.swing.border.MatteBorder(null));
        polygonsJScrollPane.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        aboutJTextArea.setEditable(false);
        aboutJTextArea.setColumns(20);
        aboutJTextArea.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        aboutJTextArea.setLineWrap(true);
        aboutJTextArea.setRows(5);
        aboutJTextArea.setText("The application simulates a ticket vending operation at a theater.\n\nThe Paradise Theater have two ticket prices – a regular price $9.00 and a matinee discount price $5.50 for early show times. Children under 10 and seniors receive the matinee price for all show times. New movies are updated weekly.\nAll tickets are taxed at a current rate of 8.9% sales tax.\n\nOCR technology by Image Recognition Integrated Systems S.A.\nCopyright© 1987 - 2014, I.R.I.S. S.A.  All rights reserved.\n\nThe Paradise Theater Inc.");
        aboutJTextArea.setWrapStyleWord(true);
        aboutJTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aboutJTextArea.setMargin(new java.awt.Insets(100, 100, 100, 100));
        aboutJTextArea.setSelectedTextColor(new java.awt.Color(51, 157, 107));
        aboutJTextArea.setSelectionColor(new java.awt.Color(153, 153, 153));
        polygonsJScrollPane.setViewportView(aboutJTextArea);

        getContentPane().add(polygonsJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 650, 320));

        headerJPanel.setBackground(new java.awt.Color(0, 204, 0));
        headerJPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerJPanelMouseDragged(evt);
            }
        });
        headerJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerJPanelMousePressed(evt);
            }
        });
        headerJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleJLabel.setText("Box Office Ticket Vending Technology");
        headerJPanel.add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 760, 80));

        exitJLabel.setBackground(new java.awt.Color(255, 51, 51));
        exitJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exitJLabel.setForeground(new java.awt.Color(255, 0, 51));
        exitJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeIcon.png"))); // NOI18N
        exitJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitJLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitJLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitJLabelMouseReleased(evt);
            }
        });
        headerJPanel.add(exitJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 50, 40));

        logoLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Movie_Projector_100px_4.png"))); // NOI18N
        headerJPanel.add(logoLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 110, 120));

        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Star_Filled_30px.png"))); // NOI18N
        headerJPanel.add(logoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 50, -1));

        logoLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Star_Filled_30px.png"))); // NOI18N
        headerJPanel.add(logoLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 40));

        logoLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Popcorn_100px.png"))); // NOI18N
        headerJPanel.add(logoLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 110, 140));

        logoLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Picture1.png"))); // NOI18N
        headerJPanel.add(logoLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 110));

        getContentPane().add(headerJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 291));

        authorJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        authorJLabel.setForeground(new java.awt.Color(204, 204, 204));
        authorJLabel.setText("Anh Dao");
        getContentPane().add(authorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 690, -1, 30));

        getinTouchJLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        getinTouchJLabel.setForeground(new java.awt.Color(0, 102, 51));
        getinTouchJLabel.setText("Get Connected");
        getContentPane().add(getinTouchJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 170, 30));

        twitterLogoJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        twitterLogoJLabel.setForeground(new java.awt.Color(0, 102, 51));
        twitterLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_QR_Code_30px_1.png"))); // NOI18N
        twitterLogoJLabel.setText("f");
        getContentPane().add(twitterLogoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 660, 30, 30));

        facebookLogoJLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        facebookLogoJLabel.setForeground(new java.awt.Color(0, 102, 51));
        facebookLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_WhatsApp_30px.png"))); // NOI18N
        facebookLogoJLabel.setText("f");
        getContentPane().add(facebookLogoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 30, 30));

        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_3D_Glasses_96px.png"))); // NOI18N
        getContentPane().add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 110, 120));

        logoLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_4k_100px_5.png"))); // NOI18N
        getContentPane().add(logoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, 120));

        getAccessibleContext().setAccessibleName("About Form");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exits the JDialog
     *
     * @param evt ActionEvent performed by closeJButton
     */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // Dispose the About from only
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed
     /**
     * drag the form by pressing the top panel
     */
    int xy;
    int xx;
    /**
     * drag the form by pressing the top panel
     *
     * @param evt MouseDragged performed by headerJPanel
     */
    private void headerJPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerJPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerJPanelMouseDragged

       /**
     * get the location of the mouse
     *
     * @param evt MousePressed performed by headerJPanelMouse
     */
    private void headerJPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerJPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerJPanelMousePressed

    /**
     * customizes the exit JButton -- spice the 2D design
     *
     * @param evt MouseExited performed by closeJLabel
     */
    private void exitJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMouseExited
        // TODO add your handling code here:
        exitJLabel.setBackground(myColor1);
        exitJLabel.setOpaque(false);
    }//GEN-LAST:event_exitJLabelMouseExited

    /**
     * set color when mouse entered
     */
    Color myColor1 = new Color(0, 102, 51);
    Color myColor2 = new Color(51, 157, 107);
     /**
     * highlight color when mouse entered
     *
     * @param evt MouseEvent performed by closeJLabelMouseEntered
     */
    private void exitJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMouseEntered
        // TODO add your handling code here:
        exitJLabel.setOpaque(true);
        exitJLabel.setBackground(myColor2);
    }//GEN-LAST:event_exitJLabelMouseEntered

    /**
     * Exits the application
     *
     * @param evt MouseEvent performed by closeJLabel
     */
    private void exitJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_exitJLabelMouseClicked

     /**
     * set color back to normal when release mouse
     *
     * @param evt MouseEvent performed by closeJLabelMouseReleased
     */
    private void exitJLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMouseReleased
        // TODO add your handling code here:
        exitJLabel.setBackground(myColor1);
        exitJLabel.setOpaque(false);
    }//GEN-LAST:event_exitJLabelMouseReleased

    
     /**
     * change color when mouse pressed
     *
     * @param evt MouseEvent performed by exitJLabelMousePressed
     */
    private void exitJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMousePressed
        // TODO add your handling code here:
        exitJLabel.setOpaque(true);
        exitJLabel.setBackground(Color.RED);
    }//GEN-LAST:event_exitJLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutJDialog dialog = new AboutJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutJTextArea;
    private javax.swing.JLabel authorJLabel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel exitJLabel;
    private javax.swing.JLabel facebookLogoJLabel;
    private javax.swing.JLabel getinTouchJLabel;
    private javax.swing.JLabel googleLogoJLabel;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JLabel logoLabel3;
    private javax.swing.JLabel logoLabel4;
    private javax.swing.JLabel logoLabel6;
    private javax.swing.JLabel logoLabel7;
    private javax.swing.JLabel logoLabel8;
    private javax.swing.JScrollPane polygonsJScrollPane;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel twitterLogoJLabel;
    private javax.swing.JLabel warningJLabel;
    // End of variables declaration//GEN-END:variables
}
